In [2]:
import numpy as np

In [3]:
array=np.array([[1,2],[3,4]])
print(array)

[[1 2]
 [3 4]]


In [4]:
print(array.shape)

(2, 2)


In [5]:
array=np.array([[1,2],[3,4],[5,6]])
print(array)

[[1 2]
 [3 4]
 [5 6]]


In [6]:
print(array.shape)

(3, 2)


In [10]:
array=np.array([[1,2,3],[4,5,6],[7,8,9]])
for i in range(3):
    row = array[i]
    print("{}|{}|{}".format(row[0], row[1], row[2]))
    print("_ _ _")

1|2|3
_ _ _
4|5|6
_ _ _
7|8|9
_ _ _


In [12]:
print(array.shape)

(3, 3)


In [13]:
num1=[1,1,1,1,1]
num2=[1,1,1,1,1]

In [14]:
num1+num2

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

In [15]:
num1 = [1, 1, 1, 1, 1]

num2 = [1, 1, 1, 1, 1]

num3 = [ ] #create a holder list


for i in range(len(num1)): #a for loop that loops over every value in the loop based on the side of the array

    num3.append(num1[i] + num2[i]) #add the sum of the values at the ith position of the arrays and save them to num3


print(num3)

[2, 2, 2, 2, 2]


In [17]:
array1=np.array([1,1,1,1])
array2=np.array([1,1,1,1])

In [18]:
print(array1+array2)

[2 2 2 2]


In [19]:
array1=np.array([2,3,4])
array2=np.array([6,32,7])

In [21]:
print(array1*array2)

[12 96 28]


In [22]:
array1=np.array([3,4,5])
array2=np.array([6,7,8])

In [23]:
print(array1-array2)

[-3 -3 -3]


In [24]:
array1=np.array([9,16,25])
array2=np.array([3,4,5])

In [25]:
print(array1/array2)

[3. 4. 5.]


In [26]:
arr1 = np.array([1, 2, 3, 4, 5])

arr2 = np.array([2, 3, 4, 5, 6])

print(arr1+5)

[ 6  7  8  9 10]
